[build]
  base = "ist-app"
  command = "npm run build"
  publish = "ist-app/dist"

[functions]
  directory = "ist-app/netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
